import { 
  Calendar, 
  CheckCircle, 
  Clock, 
  Rocket, 
  Target, 
  Zap,
  Code,
  Database,
  Server,
  Cloud
} from "lucide-react";
import { TimelineItem } from "../components/RadialOrbitalTimeline";

/**
 * Dados de exemplo para o componente RadialOrbitalTimeline
 * Use este arquivo como referência para criar seus próprios dados
 */
export const exampleTimelineData: TimelineItem[] = [
  {
    id: 1,
    title: "Início do Projeto",
    date: "2024-01-15",
    content: "Projeto iniciado com planejamento inicial e definição de escopo.",
    category: "Planning",
    icon: Calendar,
    relatedIds: [2, 3],
    status: "completed",
    energy: 100,
  },
  {
    id: 2,
    title: "Desenvolvimento Backend",
    date: "2024-02-01",
    content: "Início do desenvolvimento da API e integração com banco de dados.",
    category: "Development",
    icon: Server,
    relatedIds: [1, 4, 5],
    status: "completed",
    energy: 85,
  },
  {
    id: 3,
    title: "Design UI/UX",
    date: "2024-02-10",
    content: "Criação dos wireframes e protótipos de interface.",
    category: "Design",
    icon: Target,
    relatedIds: [1, 4],
    status: "completed",
    energy: 90,
  },
  {
    id: 4,
    title: "Desenvolvimento Frontend",
    date: "2024-03-01",
    content: "Implementação da interface do usuário e componentes React.",
    category: "Development",
    icon: Code,
    relatedIds: [2, 3, 6],
    status: "in-progress",
    energy: 75,
  },
  {
    id: 5,
    title: "Configuração do Banco de Dados",
    date: "2024-03-15",
    content: "Setup do banco de dados e migrações iniciais.",
    category: "Infrastructure",
    icon: Database,
    relatedIds: [2, 7],
    status: "in-progress",
    energy: 60,
  },
  {
    id: 6,
    title: "Testes e QA",
    date: "2024-04-01",
    content: "Início dos testes automatizados e revisão de qualidade.",
    category: "Testing",
    icon: CheckCircle,
    relatedIds: [4],
    status: "pending",
    energy: 30,
  },
  {
    id: 7,
    title: "Deploy em Produção",
    date: "2024-04-15",
    content: "Configuração do ambiente de produção e deploy inicial.",
    category: "Deployment",
    icon: Cloud,
    relatedIds: [5, 6],
    status: "pending",
    energy: 20,
  },
  {
    id: 8,
    title: "Otimização de Performance",
    date: "2024-05-01",
    content: "Análise e otimização de performance da aplicação.",
    category: "Optimization",
    icon: Zap,
    relatedIds: [4, 7],
    status: "pending",
    energy: 10,
  },
];

