import { useForm } from 'react-hook-form';
import { useParams, useNavigate } from 'react-router-dom';
import { useAuth } from '../contexts/AuthContext';
import { useEquipmentCache } from '../contexts/EquipmentCacheContext';
import { useState } from 'react';
import PageHeader from '../components/PageHeader';
import { useErrorHandler } from '../hooks/useErrorHandler';
import { useTranslation } from '../hooks/useTranslation';
import { useHaptics } from '../hooks/useHaptics';
import { ButtonSkeleton } from '../components/skeletons';
import ExtinguisherForm from '../components/forms/ExtinguisherForm';
import HoseForm from '../components/forms/HoseForm';
import ScbaForm from '../components/forms/ScbaForm';
import MultigasForm from '../components/forms/MultigasForm';
import FoamChamberForm from '../components/forms/FoamChamberForm';
import CannonMonitorForm from '../components/forms/CannonMonitorForm';
import EyewashForm from '../components/forms/EyewashForm';
import AlarmForm from '../components/forms/AlarmForm';
import ShelterForm from '../components/forms/ShelterForm';
import { saveNewExtinguisher } from '../utils/extinguisherOperations';
import { saveNewHose } from '../utils/hoseOperations';
import { saveNewSCBA } from '../utils/scbaOperations';
import { saveNewMultigasDetector } from '../utils/multigasOperations';
import { saveNewFoamChamber } from '../utils/foamChamberOperations';
import { saveNewCannonMonitor } from '../utils/cannonMonitorOperations';
import { saveNewEyewashStation } from '../utils/eyewashOperations';
import { saveNewAlarmSystem } from '../utils/alarmOperations';
import { saveNewShelter } from '../utils/shelterOperations';
import { generateAutoEquipmentId } from '../utils/equipmentIdGenerator';
import { saveCustomEquipment, getAllCustomEquipmentTypes, type CustomEquipmentType } from '../utils/customEquipmentOperations';
import CustomEquipmentForm from '../components/forms/CustomEquipmentForm';
import { useState as useStateReact, useEffect, useCallback } from 'react';
import { logger } from '../utils/logger';
import HelpTip from '../components/HelpTip';
import { supabase } from '../lib/supabase';
import { notifyEquipmentRegistered, notifyEquipmentRegistrationError, scheduleInspectionReminders } from '../utils/notificationUtils';
import { useNotifications } from '../hooks/useNotifications';
import { useConfirm } from '../hooks/useConfirm';
import ConfirmationModal from '../components/ConfirmationModal';

import InstructionsPanel from '../components/InstructionsPanel';
import AddEquipmentTour from '../components/AddEquipmentTour';

const AddEquipmentPage = () => {
  const { type } = useParams<{ type: string }>();
  const navigate = useNavigate();
  const { user, profile } = useAuth();
  const { refreshCache } = useEquipmentCache();
  const { executeWithFeedback, showInfo } = useErrorHandler();
  const { t } = useTranslation();
  const haptics = useHaptics();
  const { permissionStatus, requestPermission } = useNotifications();
  const { isOpen, confirmData, showConfirm, handleConfirm, handleCancel } = useConfirm();
  const [loading, setLoading] = useState(false);
  const [isCustomType, setIsCustomType] = useStateReact(false);
  const [customTypeId, setCustomTypeId] = useStateReact<string | null>(null);
  const [customType, setCustomType] = useStateReact<CustomEquipmentType | null>(null);
  const [customEquipmentCount, setCustomEquipmentCount] = useStateReact<number | null>(null);
  const [autoGeneratedId, setAutoGeneratedId] = useStateReact<string | null>(null);
  const { register, handleSubmit, formState: { errors }, watch, setValue } = useForm<Record<string, any>>();

  // Verifica se é tipo customizado e conta equipamentos existentes
  useEffect(() => {
    const checkCustomType = async () => {
      if (!type || !type.startsWith('custom-')) {
        setIsCustomType(false);
        setCustomEquipmentCount(null);
        return;
      }

      try {
        const slug = type.replace('custom-', '');
        const customTypes = await getAllCustomEquipmentTypes();
        const foundType = customTypes.find(t => t.slug === slug);
        
        if (foundType) {
          setIsCustomType(true);
          setCustomTypeId(foundType.id);
          setCustomType(foundType);
          
          // Conta equipamentos customizados do usuário para mostrar limite
          if (user && profile?.plan === 'trial') {
            try {
              const { supabase } = await import('../lib/supabase');
              const { count, error: countError } = await (supabase
                .from('custom_equipment' as any)
                .select('*', { count: 'exact', head: true })
                .eq('user_id', user.id));
              if (countError) {
                logger.warn('Erro ao contar equipamentos customizados', 'equipment', countError);
                setCustomEquipmentCount(null);
              } else {
                setCustomEquipmentCount(count || 0);
              }
            } catch (error) {
              logger.error('Erro ao contar equipamentos customizados', 'equipment', error);
              setCustomEquipmentCount(null);
            }
          } else {
            setCustomEquipmentCount(null);
          }
        } else {
          setIsCustomType(false);
          setCustomEquipmentCount(null);
        }
      } catch (error) {
        logger.error('Erro ao verificar tipo customizado', 'equipment', error);
        setIsCustomType(false);
        setCustomEquipmentCount(null);
      }
    };

    checkCustomType();
  }, [type, user, profile, setIsCustomType, setCustomTypeId, setCustomType, setCustomEquipmentCount]);

  const getEquipmentIdField = useCallback((): { name: string; label: string } => {
    if (isCustomType && customType) {
      return { name: customType.id_field_name || 'id_equipamento', label: customType.id_field_label || 'ID do Equipamento' };
    }

    switch (type) {
      case 'extintor':
        return { name: 'numero_identificacao', label: 'Nº Identificação' };
      case 'mangueira':
        return { name: 'id_mangueira', label: 'ID Mangueira' };
      case 'scba':
        return { name: 'numero_serie_equipamento', label: 'Nº Série Equipamento' };
      case 'multigas':
        return { name: 'id_equipamento', label: 'ID Equipamento' };
      case 'camara_espuma':
        return { name: 'id_camara', label: 'ID Câmara' };
      case 'canhao_monitor':
        return { name: 'id_equipamento', label: 'ID Equipamento' };
      case 'chuveiro_lavaolhos':
        return { name: 'id_equipamento', label: 'ID Equipamento' };
      case 'alarme':
        return { name: 'id_sistema', label: 'ID Sistema' };
      case 'abrigo':
        return { name: 'id_abrigo', label: 'ID Abrigo' };
      default:
        return { name: 'equipment_id', label: 'ID do Equipamento' };
    }
  }, [isCustomType, customType, type]);

  // Gera ID automático quando o tipo de equipamento e usuário estão disponíveis
  useEffect(() => {
    const generateInitialId = async () => {
      if (!type || !user?.id) return;

      try {
        const idField = getEquipmentIdField();
        if (!idField) return;

        let generatedId: string;

        // Para equipamentos customizados, usa lógica diferente
        if (isCustomType && customType) {
          const prefix = customType.slug?.toUpperCase().substring(0, 3) || 'CUS';
          
          try {
            const { data: generatedIdFromDb, error: genError } = await (supabase.rpc as any)('generate_unique_equipment_id', {
              p_table_name: 'custom_equipment',
              p_id_field_name: 'id_equipamento',
              p_prefix: prefix,
              p_user_id: user.id,
            });
            
            if (genError || !generatedIdFromDb || typeof generatedIdFromDb !== 'string') {
              throw new Error(t('equipment.errorCustomIdGeneration', { defaultValue: 'Erro ao gerar ID customizado' }));
            }
            
            generatedId = generatedIdFromDb;
          } catch {
            // Fallback para equipamentos customizados
            const timestampMs = Date.now();
            const random = Math.floor(Math.random() * 1000000).toString().padStart(6, '0');
            const uuidPart = Math.random().toString(36).substring(2, 8).toUpperCase();
            generatedId = `${prefix}-${timestampMs}-${random}-${uuidPart}`;
            logger.warn('ID customizado gerado por fallback client-side', 'equipment', { generatedId });
          }
        } else {
          // Para equipamentos padrão, usa a função normal
          generatedId = await generateAutoEquipmentId(type, user.id);
        }

        setAutoGeneratedId(generatedId);
        
        // Preenche o campo com o ID gerado
        setValue(idField.name, generatedId);
      } catch (error) {
        logger.error('Erro ao gerar ID inicial automático', 'equipment', error);
        // Não bloqueia o formulário se falhar, o usuário pode inserir manualmente
      }
    };

    generateInitialId();
  }, [type, user?.id, isCustomType, customType, setValue, getEquipmentIdField, setAutoGeneratedId, t]);

  const getEquipmentTypeName = (type: string) => {
    if (isCustomType && customType) {
      return customType.name;
    }

    const typeMap: Record<string, string> = {
      extintor: t('equipment.extinguisher'),
      mangueira: t('equipment.hose'),
      camara_espuma: t('equipment.foamChamber'),
      canhao_monitor: t('equipment.cannonMonitor'),
      chuveiro_lavaolhos: t('equipment.eyewash'),
      alarme: t('equipment.alarm'),
      multigas: t('equipment.multigas'),
      scba: t('equipment.scba'),
      abrigo: t('equipment.shelter'),
    };
    return typeMap[type] || type.charAt(0).toUpperCase() + type.slice(1).replace(/_/g, ' ');
  };

  const equipmentTypeName = type ? getEquipmentTypeName(type) : t('equipment.title');
  const instructionType = isCustomType ? 'add_custom' : `add_${type}`;

  const onSubmit = async (formData: Record<string, any>) => {
    if (!user || !type) return;
    setLoading(true);

    // data_cadastro não existe em todas as tabelas
    // Tabelas COM data_cadastro: multigas, camara_espuma, canhao_monitor, chuveiro_lavaolhos, alarme
    // Tabelas SEM data_cadastro: extintor, mangueira, scba, abrigo
    const dataToInsert: Record<string, any> = {
      ...formData,
      user_id: user.id,
    };

    // Adiciona data_cadastro apenas para tipos que suportam essa coluna
    const tablesWithDataCadastro = ['multigas', 'camara_espuma', 'canhao_monitor', 'chuveiro_lavaolhos', 'alarme'];
    if (tablesWithDataCadastro.includes(type)) {
      dataToInsert.data_cadastro = new Date().toISOString().split('T')[0];
    }

    let saveFunction: () => Promise<boolean>;
    let generatedId: string | null = null; // Armazena o ID gerado para mostrar na mensagem

    switch (type) {
      case 'extintor': {
        // Gera ID automático se não fornecido
        let numeroIdentificacao = (formData.numero_identificacao?.trim() || formData.equipment_id?.trim() || '').trim();
        if (!numeroIdentificacao || numeroIdentificacao === '') {
          try {
            numeroIdentificacao = await generateAutoEquipmentId(type, user.id);
            generatedId = numeroIdentificacao;
          } catch (error) {
            logger.error('Erro ao gerar ID automático para extintor', 'equipment', error);
            throw new Error(t('equipment.errorGenerateId', { defaultValue: 'Falha ao gerar ID automático do equipamento. Tente inserir um ID manualmente.' }));
          }
        }
        // Garante que o ID não está vazio antes de salvar
        if (!numeroIdentificacao || numeroIdentificacao.trim() === '') {
          throw new Error(t('equipment.errorNumberIdRequired', { defaultValue: 'Número de identificação é obrigatório' }));
        }
        
        // Extrai dados de specifications se existirem (compatibilidade com formulário antigo)
        const extinguisherData: Record<string, any> = {
          ...dataToInsert,
          numero_identificacao: numeroIdentificacao.trim(),
          numero_serie: formData.numero_serie?.trim() || undefined,
        };
        
        // Se houver specifications, extrai os campos para o nível superior
        if (formData.specifications) {
          if (formData.specifications.tipo_agente) {
            extinguisherData.tipo_agente = formData.specifications.tipo_agente;
          }
          if (formData.specifications.capacidade !== undefined) {
            extinguisherData.capacidade = formData.specifications.capacidade;
          }
          // Remove specifications para não tentar salvar essa coluna inexistente
          delete extinguisherData.specifications;
        }
        
        saveFunction = () => saveNewExtinguisher(extinguisherData as Parameters<typeof saveNewExtinguisher>[0]);
        break;
      }
      case 'mangueira': {
        let idMangueira = (formData.id_mangueira?.trim() || formData.equipment_id?.trim() || '').trim();
        if (!idMangueira || idMangueira === '') {
          try {
            idMangueira = await generateAutoEquipmentId(type, user.id);
            generatedId = idMangueira;
          } catch (error) {
            logger.error('Erro ao gerar ID automático para mangueira', 'equipment', error);
            throw new Error(t('equipment.errorGenerateId', { defaultValue: 'Falha ao gerar ID automático do equipamento. Tente inserir um ID manualmente.' }));
          }
        }
        // Garante que o ID não está vazio antes de salvar
        if (!idMangueira || idMangueira.trim() === '') {
          throw new Error(t('equipment.errorHoseIdRequired', { defaultValue: 'ID da mangueira é obrigatório' }));
        }
        // Extrai dados de specifications se existirem
        const hoseData: Record<string, any> = {
          ...dataToInsert,
          id_mangueira: idMangueira.trim(),
          numero_serie: formData.specifications?.numero_serie?.trim() || formData.numero_serie?.trim() || undefined,
        };
        
        // Se houver specifications, extrai os campos
        if (formData.specifications) {
          if (formData.specifications.marca) {
            hoseData.marca = formData.specifications.marca;
          }
          if (formData.specifications.diametro !== undefined) {
            hoseData.diametro = formData.specifications.diametro;
          }
          if (formData.specifications.tipo) {
            hoseData.tipo = formData.specifications.tipo;
          }
          if (formData.specifications.comprimento !== undefined) {
            hoseData.comprimento = formData.specifications.comprimento;
          }
          if (formData.specifications.ano_fabricacao !== undefined) {
            hoseData.ano_fabricacao = formData.specifications.ano_fabricacao;
          }
          delete hoseData.specifications;
        }
        
        saveFunction = () => saveNewHose(hoseData as Parameters<typeof saveNewHose>[0]);
        break;
      }
      case 'scba': {
        let numeroSerie = (formData.numero_serie_equipamento?.trim() || formData.equipment_id?.trim() || '').trim();
        if (!numeroSerie || numeroSerie === '') {
          try {
            numeroSerie = await generateAutoEquipmentId(type, user.id);
            generatedId = numeroSerie;
          } catch (error) {
            logger.error('Erro ao gerar ID automático para SCBA', 'equipment', error);
            throw new Error(t('equipment.errorGenerateId', { defaultValue: 'Falha ao gerar ID automático do equipamento. Tente inserir um ID manualmente.' }));
          }
        }
        // Garante que o ID não está vazio antes de salvar
        if (!numeroSerie || numeroSerie.trim() === '') {
          throw new Error(t('equipment.errorSerialNumberRequired', { defaultValue: 'Número de série do equipamento é obrigatório' }));
        }
        saveFunction = () => saveNewSCBA({
          numero_serie_equipamento: numeroSerie.trim(),
          ...dataToInsert,
        });
        break;
      }
      case 'multigas': {
        let idEquipamentoMultigas = (formData.id_equipamento?.trim() || formData.equipment_id?.trim() || '').trim();
        // Se estiver vazio ou undefined, gera automaticamente
        if (!idEquipamentoMultigas || idEquipamentoMultigas === '') {
          try {
            idEquipamentoMultigas = await generateAutoEquipmentId(type, user.id);
            generatedId = idEquipamentoMultigas;
          } catch (error) {
            logger.error('Erro ao gerar ID automático para multigas', 'equipment', error);
            throw new Error(t('equipment.errorGenerateId', { defaultValue: 'Falha ao gerar ID automático do equipamento. Tente inserir um ID manualmente.' }));
          }
        }
        // Garante que o ID não está vazio antes de salvar
        if (!idEquipamentoMultigas || idEquipamentoMultigas.trim() === '') {
          throw new Error(t('equipment.errorIdRequired', { defaultValue: 'ID do equipamento é obrigatório' }));
        }
        saveFunction = () => saveNewMultigasDetector({
          id_equipamento: idEquipamentoMultigas.trim(),
          ...dataToInsert,
        });
        break;
      }
      case 'camara_espuma': {
        let idCamara = (formData.id_camara?.trim() || formData.equipment_id?.trim() || '').trim();
        if (!idCamara || idCamara === '') {
          try {
            idCamara = await generateAutoEquipmentId(type, user.id);
            generatedId = idCamara;
          } catch (error) {
            logger.error('Erro ao gerar ID automático para câmara de espuma', 'equipment', error);
            throw new Error(t('equipment.errorGenerateId', { defaultValue: 'Falha ao gerar ID automático do equipamento. Tente inserir um ID manualmente.' }));
          }
        }
        // Garante que o ID não está vazio antes de salvar
        if (!idCamara || idCamara.trim() === '') {
          throw new Error(t('equipment.errorChamberIdRequired', { defaultValue: 'ID da câmara é obrigatório' }));
        }
        // Se numero_mcs for "outro", usa o valor de numero_mcs_custom
        let numeroMCS = formData.numero_mcs;
        if (numeroMCS === 'outro' && formData.numero_mcs_custom) {
          numeroMCS = formData.numero_mcs_custom.trim();
        }
        saveFunction = () => saveNewFoamChamber({
          id_camara: idCamara.trim(),
          localizacao: formData.localizacao,
          numero_mcs: numeroMCS || undefined,
          numero_serie: formData.numero_serie?.trim() || undefined,
          latitude: formData.latitude ? Number(formData.latitude) : undefined,
          longitude: formData.longitude ? Number(formData.longitude) : undefined,
          ...dataToInsert,
        });
        break;
      }
      case 'canhao_monitor': {
        let idEquipamentoCanhao = (formData.id_equipamento?.trim() || formData.equipment_id?.trim() || '').trim();
        if (!idEquipamentoCanhao || idEquipamentoCanhao === '') {
          try {
            idEquipamentoCanhao = await generateAutoEquipmentId(type, user.id);
            generatedId = idEquipamentoCanhao;
          } catch (error) {
            logger.error('Erro ao gerar ID automático para canhão monitor', 'equipment', error);
            throw new Error(t('equipment.errorGenerateId', { defaultValue: 'Falha ao gerar ID automático do equipamento. Tente inserir um ID manualmente.' }));
          }
        }
        // Garante que o ID não está vazio antes de salvar
        if (!idEquipamentoCanhao || idEquipamentoCanhao.trim() === '') {
          throw new Error(t('equipment.errorIdRequired', { defaultValue: 'ID do equipamento é obrigatório' }));
        }
        saveFunction = () => saveNewCannonMonitor({
          id_equipamento: idEquipamentoCanhao.trim(),
          localizacao: formData.localizacao,
          numero_serie: formData.numero_serie?.trim() || undefined,
          latitude: formData.latitude ? Number(formData.latitude) : undefined,
          longitude: formData.longitude ? Number(formData.longitude) : undefined,
          ...dataToInsert,
        });
        break;
      }
      case 'chuveiro_lavaolhos': {
        let idEquipamentoChuveiro = (formData.id_equipamento?.trim() || formData.equipment_id?.trim() || '').trim();
        if (!idEquipamentoChuveiro || idEquipamentoChuveiro === '') {
          try {
            idEquipamentoChuveiro = await generateAutoEquipmentId(type, user.id);
            generatedId = idEquipamentoChuveiro;
          } catch (error) {
            logger.error('Erro ao gerar ID automático para chuveiro lava-olhos', 'equipment', error);
            throw new Error(t('equipment.errorGenerateId', { defaultValue: 'Falha ao gerar ID automático do equipamento. Tente inserir um ID manualmente.' }));
          }
        }
        // Garante que o ID não está vazio antes de salvar
        if (!idEquipamentoChuveiro || idEquipamentoChuveiro.trim() === '') {
          throw new Error(t('equipment.errorIdRequired', { defaultValue: 'ID do equipamento é obrigatório' }));
        }
        saveFunction = () => saveNewEyewashStation({
          id_equipamento: idEquipamentoChuveiro.trim(),
          localizacao: formData.localizacao,
          numero_serie: formData.numero_serie?.trim() || undefined,
          latitude: formData.latitude ? Number(formData.latitude) : undefined,
          longitude: formData.longitude ? Number(formData.longitude) : undefined,
          ...dataToInsert,
        });
        break;
      }
      case 'alarme': {
        let idSistema = (formData.id_sistema?.trim() || formData.equipment_id?.trim() || '').trim();
        if (!idSistema || idSistema === '') {
          try {
            idSistema = await generateAutoEquipmentId(type, user.id);
            generatedId = idSistema;
          } catch (error) {
            logger.error('Erro ao gerar ID automático para alarme', 'equipment', error);
            throw new Error(t('equipment.errorGenerateId', { defaultValue: 'Falha ao gerar ID automático do equipamento. Tente inserir um ID manualmente.' }));
          }
        }
        // Garante que o ID não está vazio antes de salvar
        if (!idSistema || idSistema.trim() === '') {
          throw new Error(t('equipment.errorSystemIdRequired', { defaultValue: 'ID do sistema é obrigatório' }));
        }
        saveFunction = () => saveNewAlarmSystem({
          id_sistema: idSistema.trim(),
          localizacao: formData.localizacao || '',
          numero_serie: formData.numero_serie?.trim() || undefined,
          ...dataToInsert,
        });
        break;
      }
      case 'abrigo': {
        let idAbrigo = (formData.id_abrigo?.trim() || formData.equipment_id?.trim() || '').trim();
        if (!idAbrigo || idAbrigo === '') {
          try {
            idAbrigo = await generateAutoEquipmentId(type, user.id);
            generatedId = idAbrigo;
          } catch (error) {
            logger.error('Erro ao gerar ID automático para abrigo', 'equipment', error);
            throw new Error(t('equipment.errorGenerateId', { defaultValue: 'Falha ao gerar ID automático do equipamento. Tente inserir um ID manualmente.' }));
          }
        }
        // Garante que o ID não está vazio antes de salvar
        if (!idAbrigo || idAbrigo.trim() === '') {
          throw new Error(t('equipment.errorShelterIdRequired', { defaultValue: 'ID do abrigo é obrigatório' }));
        }
        saveFunction = () => saveNewShelter({
          id_abrigo: idAbrigo.trim(),
          numero_serie: formData.numero_serie?.trim() || undefined,
          latitude: formData.latitude ? Number(formData.latitude) : undefined,
          longitude: formData.longitude ? Number(formData.longitude) : undefined,
          ...dataToInsert,
        });
        break;
      }
      default:
        // Verifica se é tipo customizado
        if (isCustomType && customTypeId) {
          const idFieldName = customType?.id_field_name || 'id_equipamento';
          let equipmentId = (formData[idFieldName]?.trim() || formData.equipment_id?.trim() || '').trim();
          
          if (!equipmentId || equipmentId === '') {
            // Gera ID automático para tipo customizado usando função atômica do banco
            const prefix = customType?.slug?.toUpperCase().substring(0, 3) || 'CUS';
            
            try {
              const { data: generatedIdFromDb, error: genError } = await (supabase.rpc as any)('generate_unique_equipment_id', {
                p_table_name: 'custom_equipment',
                p_id_field_name: 'id_equipamento',
                p_prefix: prefix,
                p_user_id: user.id,
              });
              
              if (genError) {
                logger.error('Erro ao gerar ID customizado via banco', 'equipment', genError);
                throw genError;
              }

              if (generatedIdFromDb && typeof generatedIdFromDb === 'string') {
                equipmentId = generatedIdFromDb as string;
                logger.debug('ID customizado gerado com sucesso', 'equipment', { id: equipmentId });
              } else {
                throw new Error(t('equipment.errorDatabaseEmptyResult', { defaultValue: 'Função do banco retornou resultado vazio' }));
              }
              
              generatedId = equipmentId;
            } catch (err) {
              logger.error('Erro ao gerar ID customizado, usando fallback', 'equipment', err);
              // Fallback melhorado: timestamp MS + random + UUID
              const timestampMs = Date.now();
              const random = Math.floor(Math.random() * 1000000).toString().padStart(6, '0');
              const uuidPart = Math.random().toString(36).substring(2, 8).toUpperCase();
              equipmentId = `${prefix}-${timestampMs}-${random}-${uuidPart}`;
              generatedId = equipmentId;
              logger.warn('ID customizado gerado por fallback client-side', 'equipment', { equipmentId });
            }
          }
          
          // Garante que o ID não está vazio antes de salvar
          if (!equipmentId || equipmentId.trim() === '') {
            throw new Error(t('equipment.errorIdRequired', { defaultValue: 'ID do equipamento é obrigatório' }));
          }

          const customEquipmentData: Record<string, any> = {
            equipment_type_id: customTypeId,
            id_equipamento: equipmentId.trim(),
            data_cadastro: customType?.has_data_cadastro ? new Date().toISOString().split('T')[0] : undefined,
            localizacao: customType?.requires_location ? formData.localizacao : undefined,
            numero_serie: formData.numero_serie?.trim() || undefined,
            latitude: customType?.requires_gps && formData.latitude ? Number(formData.latitude) : undefined,
            longitude: customType?.requires_gps && formData.longitude ? Number(formData.longitude) : undefined,
            custom_fields: formData.custom_fields || {},
            user_id: user.id,
          };

          saveFunction = () => saveCustomEquipment(customEquipmentData as Parameters<typeof saveCustomEquipment>[0]);
        } else {
          setLoading(false);
          return;
        }
        break;
    }

    // Monta mensagem de sucesso personalizada
    let successMessage = t('equipment.registerSuccess', { defaultValue: 'Equipamento cadastrado com sucesso!' });
    if (generatedId) {
      successMessage = t('equipment.registerSuccessWithId', { 
        defaultValue: 'Equipamento cadastrado com sucesso!\n\nID gerado automaticamente: {id}',
        id: generatedId
      });
    }

    const success = await executeWithFeedback(
      saveFunction,
      'equipment',
      successMessage,
      t('equipment.registerError', { defaultValue: 'Falha ao cadastrar equipamento. Verifique se o ID já existe.' })
    );

    if (success) {
      // Verificação contextual de permissão de notificação
      if (permissionStatus.prompt || (!permissionStatus.granted && !permissionStatus.denied)) {
        const wantNotifications = await showConfirm({
          title: t('notifications.prompt.title', { defaultValue: 'Ativar Lembretes?' }),
          message: t('notifications.prompt.message', { 
            defaultValue: 'Deseja ser lembrado automaticamente antes que este equipamento vença? Isso ajuda a manter sua segurança em dia.' 
          }),
          confirmText: t('common.yes', { defaultValue: 'Sim, Ativar' }),
          cancelText: t('common.no', { defaultValue: 'Agora Não' }),
          variant: 'info'
        });

        if (wantNotifications) {
          const granted = await requestPermission();
          if (granted) {
            showInfo(t('notifications.enabledSuccess', { defaultValue: 'Notificações ativadas com sucesso!' }));
          }
        }
      }

      // Envia notificação de sucesso e agenda lembretes
      const idField = getEquipmentIdField();
      const equipmentId = generatedId || formData[idField.name] || formData.equipment_id || '';
      const equipmentType = equipmentTypeName;
      if (equipmentId && equipmentType) {
        await notifyEquipmentRegistered(equipmentId, equipmentType);
        
        // Agenda lembretes futuros se houver data de inspeção
        const nextInspection = formData.data_proxima_inspecao || formData.data_proximo_teste || formData.data_proxima_manutencao_2_nivel;
        if (nextInspection) {
          await scheduleInspectionReminders(
            equipmentId, 
            equipmentType, 
            nextInspection, 
            `/equipment/${type}/${equipmentId}`
          );
        }
      }

      // Atualiza o cache imediatamente para que o novo equipamento apareça na lista
      try {
        await refreshCache();
      } catch (error) {
        // Log do erro mas não impede a navegação
        logger.error('Erro ao atualizar cache', 'equipment', error);
      }
      navigate(`/inspections/${type}`);
    } else {
      // Envia notificação de erro
      await notifyEquipmentRegistrationError();
    }
    
    setLoading(false);
  };

  const renderSpecificForm = () => {
    switch (type) {
      case 'extintor':
        return <ExtinguisherForm register={register} errors={errors} watch={watch} />;
      case 'mangueira':
        return <HoseForm register={register} />;
      case 'scba':
        return <ScbaForm register={register} />;
      case 'multigas':
        return <MultigasForm register={register} />;
      case 'camara_espuma':
        return <FoamChamberForm register={register} errors={errors} watch={watch} />;
      case 'canhao_monitor':
        return <CannonMonitorForm register={register} />;
      case 'chuveiro_lavaolhos':
        return <EyewashForm register={register} />;
      case 'alarme':
        return <AlarmForm register={register} />;
      case 'abrigo':
        return <ShelterForm register={register} />;
      default:
        return null;
    }
  };

  const idField = getEquipmentIdField();

  return (
    <div className="min-h-screen" style={{ backgroundColor: '#000000' }}>
      <PageHeader 
        title={{ key: 'equipment.add', defaultValue: `Adicionar ${equipmentTypeName}` }} 
        help={{
          titleKey: 'help.addEquipment.title',
          contentKey: 'help.addEquipment.content'
        }}
      />
      <main className="p-4 pb-32" style={{ backgroundColor: '#000000' }}>
        <div data-tour="add-equipment-intro">
          <InstructionsPanel equipmentType={instructionType} className="mb-6" />
        </div>
        <form onSubmit={handleSubmit(onSubmit)}>
          <div className="mb-4" data-tour="add-equipment-id">
            <div className="flex items-center gap-2 mb-1">
              <label htmlFor={idField.name} className="block text-sm font-medium" style={{ color: '#FFFFFF' }}>
                {idField.label}
              </label>
              <HelpTip 
                titleKey="help.equipmentId.title"
                contentKey="help.equipmentId.content"
              />
            </div>
            <input
              id={idField.name}
              {...register(idField.name, {
                pattern: {
                  value: /^[a-zA-Z0-9_-]+$/,
                  message: t('equipment.formHints.invalidIdFormat', { defaultValue: 'O ID pode conter apenas letras, números, hífens (-) e underscores (_)' })
                },
                maxLength: {
                  value: 100,
                  message: t('equipment.formHints.idMaxLength', { defaultValue: 'O ID deve ter no máximo 100 caracteres' })
                },
                validate: (value) => {
                  if (value && value.trim() !== '') {
                    // Remove espaços em branco no início e fim
                    const trimmed = value.trim();
                    // Verifica se não começa ou termina com hífen ou underscore
                    if (trimmed.startsWith('-') || trimmed.startsWith('_') || trimmed.endsWith('-') || trimmed.endsWith('_')) {
                      return t('equipment.formHints.invalidIdStartEnd', { defaultValue: 'O ID não pode começar ou terminar com hífen (-) ou underscore (_)' });
                    }
                    // Verifica se não tem espaços no meio
                    if (trimmed.includes(' ')) {
                      return t('equipment.formHints.noSpacesInId', { defaultValue: 'O ID não pode conter espaços' });
                    }
                  }
                  return true;
                }
              })}
              placeholder={autoGeneratedId ? autoGeneratedId : t('equipment.formHints.leaveEmptyAutoGenerate')}
              className="w-full p-3 bg-light-surface dark:bg-dark-surface border rounded-lg focus:ring-2 focus:ring-white/30 focus:outline-none" 
              style={{ backgroundColor: '#1A1A1A', borderColor: '#2A2A2A', borderWidth: '1px', color: '#FFFFFF' }}
            />
            <p className="text-xs mt-1.5" style={{ color: '#B0B0B0' }}>
              💡 {autoGeneratedId 
                ? t('equipment.formHints.idAutoGenerated', { defaultValue: 'ID gerado automaticamente. Você pode alterar se desejar.' })
                : t('equipment.formHints.optionalAutoGenerate', { defaultValue: 'Opcional: Se deixar vazio, um ID único será gerado automaticamente' })
              }
            </p>
            {errors[idField.name as string] && (
              <p className="text-sm text-status-error mt-1">
                {String(errors[idField.name as string]?.message)}
              </p>
            )}
          </div>
          
          {/* Campo de localização removido - já está nos formulários específicos (FoamChamberForm, CannonMonitorForm, EyewashForm, AlarmForm) */}

          {/* Campo de localização para tipos customizados */}
          {isCustomType && customType?.requires_location && (
            <div className="mb-4">
              <label htmlFor="localizacao" className="block text-sm font-medium mb-1" style={{ color: '#FFFFFF' }}>{t('equipment.location')}</label>
              <input
                id="localizacao"
                {...register('localizacao')}
                className="w-full p-3 bg-light-surface dark:bg-dark-surface border rounded-lg focus:ring-2 focus:ring-white/30 focus:outline-none" 
                style={{ backgroundColor: '#1A1A1A', borderColor: '#2A2A2A', borderWidth: '1px', color: '#FFFFFF' }}
              />
            </div>
          )}

          {/* Campo de número de série para tipos customizados */}
          {isCustomType && (
            <div className="mb-4">
              <label htmlFor="numero_serie" className="block text-sm font-medium mb-1" style={{ color: '#FFFFFF' }}>
                {t('equipment.serialNumber', { defaultValue: 'Nº de Série' })} <span className="text-gray-400 text-xs">{t('equipment.formHints.optional')}</span>
              </label>
              <input
                id="numero_serie"
                type="text"
                placeholder="Ex: SN123456"
                {...register('numero_serie')}
                className="w-full p-3 bg-light-surface dark:bg-dark-surface border rounded-lg focus:ring-2 focus:ring-white/30 focus:outline-none" 
                style={{ backgroundColor: '#1A1A1A', borderColor: '#2A2A2A', borderWidth: '1px', color: '#FFFFFF' }}
              />
            </div>
          )}

          {/* Campos de GPS para tipos customizados */}
          {isCustomType && customType?.requires_gps && (
            <div className="mb-4">
              <div className="flex items-center gap-2 mb-1">
                <label className="block text-sm font-medium" style={{ color: '#FFFFFF' }}>
                  Coordenadas GPS <span className="text-gray-400 text-xs">(opcional)</span>
                </label>
                <HelpTip 
                  titleKey="help.gps.title"
                  contentKey="help.gps.content"
                />
              </div>
              <div className="grid grid-cols-2 gap-3">
                <div>
                  <label htmlFor="latitude" className="block text-xs text-gray-400 mb-1">{t('equipment.formHints.latitude')}</label>
                  <input
                    id="latitude"
                    type="number"
                    step="any"
                    placeholder="Ex: -23.5505"
                    {...register('latitude', { 
                      valueAsNumber: true,
                      min: { value: -90, message: 'Latitude deve estar entre -90 e 90' },
                      max: { value: 90, message: 'Latitude deve estar entre -90 e 90' }
                    })}
                    className="w-full p-3 rounded-lg border focus:ring-2 focus:ring-white/30 focus:outline-none" 
                    style={{ backgroundColor: '#1A1A1A', borderColor: '#2A2A2A', borderWidth: '1px', color: '#FFFFFF' }}
                  />
                </div>
                <div>
                  <label htmlFor="longitude" className="block text-xs text-gray-400 mb-1">{t('equipment.formHints.longitude')}</label>
                  <input
                    id="longitude"
                    type="number"
                    step="any"
                    placeholder="Ex: -46.6333"
                    {...register('longitude', { 
                      valueAsNumber: true,
                      min: { value: -180, message: 'Longitude deve estar entre -180 e 180' },
                      max: { value: 180, message: 'Longitude deve estar entre -180 e 180' }
                    })}
                    className="w-full p-3 rounded-lg border focus:ring-2 focus:ring-white/30 focus:outline-none" 
                    style={{ backgroundColor: '#1A1A1A', borderColor: '#2A2A2A', borderWidth: '1px', color: '#FFFFFF' }}
                  />
                </div>
              </div>
              <p className="text-xs mt-1.5" style={{ color: '#B0B0B0' }}>
                💡 {t('equipment.formHints.gpsCoordinatesHint')}
              </p>
            </div>
          )}

          {/* Campos de coordenadas GPS para abrigos */}
          {type === 'abrigo' && (
            <div className="mb-4">
              <div className="flex items-center gap-2 mb-1">
                <label className="block text-sm font-medium" style={{ color: '#FFFFFF' }}>
                  {t('equipment.formHints.gpsCoordinates')} <span className="text-gray-400 text-xs">{t('equipment.formHints.optional')}</span>
                </label>
                <HelpTip 
                  titleKey="help.gps.title"
                  contentKey="help.gps.content"
                />
              </div>
              <div className="grid grid-cols-2 gap-3">
                <div>
                  <label htmlFor="latitude" className="block text-xs text-gray-400 mb-1">{t('equipment.formHints.latitude')}</label>
                  <input
                    id="latitude"
                    type="number"
                    step="any"
                    placeholder="Ex: -23.5505"
                    {...register('latitude', { 
                      valueAsNumber: true,
                      min: { value: -90, message: t('equipment.formHints.latitudeRange') },
                      max: { value: 90, message: t('equipment.formHints.latitudeRange') }
                    })}
                    className="w-full p-3 bg-light-surface dark:bg-dark-surface border rounded-lg focus:ring-2 focus:ring-white/30 focus:outline-none" 
                    style={{ backgroundColor: '#1A1A1A', borderColor: '#2A2A2A', borderWidth: '1px', color: '#FFFFFF' }}
                  />
                </div>
                <div>
                  <label htmlFor="longitude" className="block text-xs text-gray-400 mb-1">{t('equipment.formHints.longitude')}</label>
                  <input
                    id="longitude"
                    type="number"
                    step="any"
                    placeholder="Ex: -46.6333"
                    {...register('longitude', { 
                      valueAsNumber: true,
                      min: { value: -180, message: t('equipment.formHints.longitudeRange') },
                      max: { value: 180, message: t('equipment.formHints.longitudeRange') }
                    })}
                    className="w-full p-3 bg-light-surface dark:bg-dark-surface border rounded-lg focus:ring-2 focus:ring-white/30 focus:outline-none" 
                    style={{ backgroundColor: '#1A1A1A', borderColor: '#2A2A2A', borderWidth: '1px', color: '#FFFFFF' }}
                  />
                </div>
              </div>
              <p className="text-xs mt-1.5" style={{ color: '#B0B0B0' }}>
                💡 {t('equipment.formHints.gpsCoordinatesHint')}
              </p>
            </div>
          )}


          {type === 'alarme' && (
            <>
              <div className="mb-4">
                <label htmlFor="marca" className="block text-sm font-medium mb-1">Marca</label>
                <input
                  id="marca"
                  {...register('marca')}
                  className="w-full p-3 bg-light-surface dark:bg-dark-surface border rounded-lg focus:ring-2 focus:ring-white/30 focus:outline-none" style={{ backgroundColor: '#1A1A1A', borderColor: '#2A2A2A', borderWidth: '1px' }}
                />
              </div>
              <div className="mb-4">
                <label htmlFor="modelo" className="block text-sm font-medium mb-1">Modelo</label>
                <input
                  id="modelo"
                  {...register('modelo')}
                  className="w-full p-3 bg-light-surface dark:bg-dark-surface border rounded-lg focus:ring-2 focus:ring-white/30 focus:outline-none" style={{ backgroundColor: '#1A1A1A', borderColor: '#2A2A2A', borderWidth: '1px' }}
                />
              </div>
            </>
          )}

          {type === 'abrigo' && (
            <>
              <div className="mb-4">
                <label htmlFor="cliente" className="block text-sm font-medium mb-1">{t('equipment.client', { defaultValue: 'Cliente' })}</label>
                <input
                  id="cliente"
                  {...register('cliente')}
                  className="w-full p-3 bg-light-surface dark:bg-dark-surface border rounded-lg focus:ring-2 focus:ring-white/30 focus:outline-none" style={{ backgroundColor: '#1A1A1A', borderColor: '#2A2A2A', borderWidth: '1px' }}
                />
              </div>
              <div className="mb-4">
                <label htmlFor="local" className="block text-sm font-medium mb-1">{t('equipment.location')}</label>
                <input
                  id="local"
                  {...register('local')}
                  className="w-full p-3 bg-light-surface dark:bg-dark-surface border rounded-lg focus:ring-2 focus:ring-white/30 focus:outline-none" style={{ backgroundColor: '#1A1A1A', borderColor: '#2A2A2A', borderWidth: '1px' }}
                />
              </div>
            </>
          )}

          <div data-tour="add-equipment-form-body">
          {isCustomType && customTypeId ? (
            <>
              {profile?.plan === 'trial' && customEquipmentCount !== null && (
                <div className="mb-4 p-3 rounded-lg border" style={{ backgroundColor: 'rgba(252, 61, 57, 0.1)', borderColor: '#FC3D39' }}>
                  <p className="text-sm" style={{ color: '#FFFFFF' }}>
                    <strong>Limite do Plano Trial:</strong> Você já criou {customEquipmentCount} de 3 equipamentos customizados permitidos.
                    {customEquipmentCount >= 3 && (
                      <span className="block mt-1 text-red-400">
                        Limite atingido! Faça upgrade para Premium para criar equipamentos ilimitados.
                      </span>
                    )}
                  </p>
                </div>
              )}
              <CustomEquipmentForm
                equipmentTypeId={customTypeId}
                register={register}
                errors={errors}
                watch={watch}
              />
            </>
          ) : (
            renderSpecificForm()
          )}
          </div>

          <button
            data-tour="add-equipment-submit"
            type="submit"
            disabled={loading}
            onClick={() => haptics.medium()}
            className="w-full p-3 bg-white text-black font-bold rounded-lg hover:bg-gray-200 transition-colors disabled:opacity-50 disabled:cursor-not-allowed"
          >
            {loading ? <ButtonSkeleton width="w-32" /> : t('equipment.saveSuccess', { defaultValue: 'Salvar Equipamento' })}
          </button>
        </form>
      </main>
      <AddEquipmentTour hasType={!!type} />

      {confirmData && (
        <ConfirmationModal
          isOpen={isOpen}
          onClose={handleCancel}
          onConfirm={handleConfirm}
          title={confirmData.title}
          message={confirmData.message}
          isLoading={false}
          confirmText={confirmData.confirmText}
          cancelText={confirmData.cancelText}
          variant={confirmData.variant}
        />
      )}
    </div>
  );
};

export default AddEquipmentPage;
