# Define os cabeçalhos para cada aba a ser criada em uma nova planilha de UO.

locais:
  - id
  - latitude
  - longitude
  - local

extintores:
  - numero_identificacao
  - numero_selo_inmetro
  - tipo_agente
  - capacidade
  - marca_fabricante
  - ano_fabricacao
  - tipo_servico
  - data_servico
  - inspetor_responsavel
  - empresa_executante
  - data_proxima_inspecao
  - data_proxima_manutencao_2_nivel
  - data_proxima_manutencao_3_nivel
  - data_ultimo_ensaio_hidrostatico
  - aprovado_inspecao
  - observacoes_gerais
  - plano_de_acao
  - link_relatorio_pdf
  - latitude
  - longitude
  - link_foto_nao_conformidade

mangueiras:
  - id_mangueira
  - marca
  - diametro
  - tipo
  - comprimento
  - ano_fabricacao
  - data_inspecao
  - data_proximo_teste
  - resultado
  - link_certificado_pdf
  - registrado_por
  - empresa_executante
  - resp_tecnico_certificado

log_baixas_mangueiras: 
  - data_baixa
  - id_mangueira
  - motivo
  - responsavel
  - id_mangueira_substituta

abrigos:
  - id_abrigo
  - cliente
  - local
  - itens_json

inspecoes_abrigos:
  - data_inspecao
  - id_abrigo
  - status_geral
  - resultados_json
  - inspetor
  - data_proxima_inspecao

conjuntos_autonomos:
  - data_teste
  - data_validade
  - numero_serie_equipamento
  - marca
  - modelo
  - numero_serie_mascara
  - numero_serie_segundo_estagio
  - resultado_final
  - vazamento_mascara_resultado
  - vazamento_mascara_valor
  - vazamento_pressao_alta_resultado
  - vazamento_pressao_alta_valor
  - pressao_alarme_resultado
  - pressao_alarme_valor
  - link_relatorio_pdf
  - registrado_por
  - empresa_executante
  - resp_tecnico_certificado
  - data_qualidade_ar
  - status_qualidade_ar
  - obs_qualidade_ar
  - link_laudo_ar

inspecoes_scba:
  - data_inspecao
  - numero_serie_equipamento
  - status_geral
  - resultados_json
  - inspetor
  - data_proxima_inspecao

log_acoes:
  - data_correcao
  - id_equipamento
  - problema_original
  - acao_realizada
  - responsavel_acao
  - id_equipamento_substituto
  - link_foto_evidencia

log_abrigos:
  - data_acao
  - id_abrigo
  - problema_original
  - acao_realizada
  - responsavel

log_scba:
  - data_acao
  - numero_serie_equipamento
  - problema_original
  - acao_realizada
  - responsavel

log_remessas_th:
  - data_remessa
  - id_mangueira
  - ano_remessa
  - numero_boletim

log_remessas_extintores:
  - data_remessa
  - numero_identificacao
  - ano_remessa
  - numero_boletim
  
inspecoes_chuveiros_lava_olhos:
  - data_inspecao    
  - id_equipamento
  - status_geral
  - resultados_json
  - inspetor
  - data_proxima_inspecao

chuveiros_lava_olhos:
  - id_equipamento
  - localizacao
  - marca
  - modelo
  - data_cadastro
  - data_instalacao      
  - status_operacional

log_acoes_chuveiros:
  - data_acao
  - id_equipamento
  - problema_original
  - acao_realizada
  - responsavel
  - link_foto_evidencia
 
camaras_espuma_inventario:
  - id_camara
  - localizacao
  - marca
  - modelo
  - data_cadastro
inspecoes_camaras_espuma:
  - data_inspecao
  - id_camara
  - tipo_inspecao
  - status_geral
  - plano_de_acao
  - resultados_json
  - link_foto_nao_conformidade
  - inspetor
  - data_proxima_inspecao
log_acoes_camaras_espuma:
  - data_acao
  - id_camara
  - problema_original
  - acao_realizada
  - responsavel
multigas_inventario:
  - id_equipamento
  - marca
  - modelo
  - numero_serie
  - data_cadastro
  - LEL_cilindro
  - O2_cilindro
  - H2S_cilindro
  - CO_cilindro
inspecoes_multigas:
  - data_teste
  - hora_teste
  - id_equipamento
  - LEL_encontrado
  - O2_encontrado
  - H2S_encontrado
  - CO_encontrado
  - tipo_teste
  - resultado_teste
  - responsavel_nome
  - responsavel_matricula
  - proxima_calibracao
  - numero_certificado
  - link_certificado
  - observacoes
  - plano_de_acao
log_multigas:
  - data_acao
  - id_equipamento
  - problema
  - acao_realizada
  - responsavel
  - link_foto_evidencia
alarmes_inventario:
  - id_sistema
  - localizacao
  - marca
  - modelo
  - data_cadastro
alarmes_inspecoes:
  - data_inspecao
  - id_sistema
  - status_geral
  - plano_de_acao
  - resultados_json
  - link_foto_nao_conformidade
  - inspetor
  - data_proxima_inspecao
log_alarmes:
  - data_acao
  - id_sistema
  - problema_original
  - acao_realizada
  - responsavel
  - link_foto_evidencia
  
solicitacoes_suporte:
  - data_solicitacao
  - email_usuario
  - nome_usuario
  - tipo_solicitacao
  - assunto
  - mensagem
  - prioridade
  - status
  - data_resposta
  - resposta_suporte

notificacoes_pendentes:
  - timestamp
  - tipo_notificacao
  - email_destinatario
  - nome_destinatario
  - dados_json
  - status

log_baixas_extintores:
  - data_baixa
  - numero_identificacao
  - motivo_condenacao
  - responsavel_baixa
  - numero_identificacao_substituto
  - observacoes
  - link_foto_evidencia
