/*
# [Complete Operations Schema]
This migration creates all necessary tables for the complete operations functionality based on the reference app.
It includes inventory tables, inspection tables, action log tables, and auxiliary tables for all equipment types.

## Metadata:
- Schema-Category: "Structural"
- Impact-Level: "Medium"
- Requires-Backup: false
- Reversible: true (by dropping the created tables)

## Structure Details:
- Inventory tables: extintores, mangueiras, conjuntos_autonomos, inventario_multigas, inventario_camaras_espuma, inventario_canhoes_monitores, inventario_chuveiros_lava_olhos, inventario_alarmes, abrigos
- Inspection tables: inspecoes_scba, inspecoes_multigas, inspecoes_camaras_espuma, inspecoes_canhoes_monitores, inspecoes_chuveiros_lava_olhos, inspecoes_alarmes, inspecoes_abrigos
- Action log tables: log_acoes_extintores, log_acoes_scba, log_acoes_multigas, log_acoes_camaras_espuma, log_acoes_canhoes_monitores, log_acoes_chuveiros_lava_olhos, log_acoes_alarmes, log_acoes_abrigos
- Auxiliary tables: locais, log_baixa_extintores

## Security Implications:
- RLS Status: Enabled on all new tables
- Policy Changes: Yes, new policies created for all tables
- Auth Requirements: Authenticated users can manage their own data
*/

-- ============================================
-- TABELAS AUXILIARES
-- ============================================

-- Tabela de Locais
CREATE TABLE IF NOT EXISTS public.locais (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
    local_id TEXT NOT NULL UNIQUE,
    local_descricao TEXT NOT NULL,
    user_id UUID REFERENCES auth.users(id) ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS locais_user_id_idx ON public.locais(user_id);
ALTER TABLE public.locais ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Authenticated users can manage locations"
    ON public.locais FOR ALL
    USING (auth.role() = 'authenticated'::text)
    WITH CHECK (auth.role() = 'authenticated'::text);

-- ============================================
-- TABELAS DE INVENTÁRIO
-- ============================================

-- Tabela de Extintores (principal)
CREATE TABLE IF NOT EXISTS public.extintores (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
    numero_identificacao TEXT NOT NULL UNIQUE,
    numero_selo_inmetro TEXT,
    tipo_agente TEXT,
    capacidade NUMERIC,
    marca_fabricante TEXT,
    ano_fabricacao INTEGER,
    tipo_servico TEXT DEFAULT 'Cadastro',
    data_servico DATE,
    inspetor_responsavel TEXT,
    empresa_executante TEXT,
    data_proxima_inspecao DATE,
    data_proxima_manutencao_2_nivel DATE,
    data_proxima_manutencao_3_nivel DATE,
    data_ultimo_ensaio_hidrostatico DATE,
    aprovado_inspecao TEXT DEFAULT 'N/A',
    observacoes_gerais TEXT,
    plano_de_acao TEXT,
    link_relatorio_pdf TEXT,
    latitude NUMERIC,
    longitude NUMERIC,
    link_foto_nao_conformidade TEXT,
    local_id TEXT REFERENCES public.locais(local_id),
    user_id UUID REFERENCES auth.users(id) ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS extintores_user_id_idx ON public.extintores(user_id);
CREATE INDEX IF NOT EXISTS extintores_local_id_idx ON public.extintores(local_id);
ALTER TABLE public.extintores ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Authenticated users can manage extinguishers"
    ON public.extintores FOR ALL
    USING (auth.role() = 'authenticated'::text)
    WITH CHECK (auth.role() = 'authenticated'::text);

-- Tabela de Mangueiras
CREATE TABLE IF NOT EXISTS public.mangueiras (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
    id_mangueira TEXT NOT NULL UNIQUE,
    marca TEXT,
    diametro NUMERIC,
    tipo TEXT,
    comprimento NUMERIC,
    ano_fabricacao INTEGER,
    data_inspecao DATE,
    data_proximo_teste DATE,
    resultado TEXT,
    link_certificado_pdf TEXT,
    registrado_por TEXT,
    empresa_executante TEXT,
    resp_tecnico_certificado TEXT,
    user_id UUID REFERENCES auth.users(id) ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS mangueiras_user_id_idx ON public.mangueiras(user_id);
ALTER TABLE public.mangueiras ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Authenticated users can manage hoses"
    ON public.mangueiras FOR ALL
    USING (auth.role() = 'authenticated'::text)
    WITH CHECK (auth.role() = 'authenticated'::text);

-- Tabela de Conjuntos Autônomos (SCBA)
CREATE TABLE IF NOT EXISTS public.conjuntos_autonomos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
    numero_serie_equipamento TEXT NOT NULL UNIQUE,
    marca TEXT,
    modelo TEXT,
    numero_serie_mascara TEXT,
    numero_serie_segundo_estagio TEXT,
    data_teste DATE,
    data_validade DATE,
    resultado_final TEXT,
    vazamento_mascara_resultado TEXT,
    inspetor_responsavel TEXT,
    empresa_executante TEXT,
    link_relatorio_pdf TEXT,
    user_id UUID REFERENCES auth.users(id) ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS conjuntos_autonomos_user_id_idx ON public.conjuntos_autonomos(user_id);
ALTER TABLE public.conjuntos_autonomos ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Authenticated users can manage SCBA"
    ON public.conjuntos_autonomos FOR ALL
    USING (auth.role() = 'authenticated'::text)
    WITH CHECK (auth.role() = 'authenticated'::text);

-- Tabela de Inventário Multigás
CREATE TABLE IF NOT EXISTS public.inventario_multigas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
    id_equipamento TEXT NOT NULL UNIQUE,
    marca TEXT,
    modelo TEXT,
    numero_serie TEXT,
    data_cadastro DATE DEFAULT CURRENT_DATE,
    LEL_cilindro NUMERIC,
    O2_cilindro NUMERIC,
    H2S_cilindro INTEGER,
    CO_cilindro INTEGER,
    user_id UUID REFERENCES auth.users(id) ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS inventario_multigas_user_id_idx ON public.inventario_multigas(user_id);
ALTER TABLE public.inventario_multigas ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Authenticated users can manage multigas inventory"
    ON public.inventario_multigas FOR ALL
    USING (auth.role() = 'authenticated'::text)
    WITH CHECK (auth.role() = 'authenticated'::text);

-- Tabela de Inventário Câmaras de Espuma
CREATE TABLE IF NOT EXISTS public.inventario_camaras_espuma (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
    id_camara TEXT NOT NULL UNIQUE,
    localizacao TEXT,
    marca TEXT,
    modelo TEXT,
    tamanho_especifico TEXT,
    data_cadastro DATE DEFAULT CURRENT_DATE,
    user_id UUID REFERENCES auth.users(id) ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS inventario_camaras_espuma_user_id_idx ON public.inventario_camaras_espuma(user_id);
ALTER TABLE public.inventario_camaras_espuma ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Authenticated users can manage foam chambers inventory"
    ON public.inventario_camaras_espuma FOR ALL
    USING (auth.role() = 'authenticated'::text)
    WITH CHECK (auth.role() = 'authenticated'::text);

-- Tabela de Inventário Canhões Monitores
CREATE TABLE IF NOT EXISTS public.inventario_canhoes_monitores (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
    id_equipamento TEXT NOT NULL UNIQUE,
    localizacao TEXT,
    marca TEXT,
    modelo TEXT,
    data_cadastro DATE DEFAULT CURRENT_DATE,
    user_id UUID REFERENCES auth.users(id) ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS inventario_canhoes_monitores_user_id_idx ON public.inventario_canhoes_monitores(user_id);
ALTER TABLE public.inventario_canhoes_monitores ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Authenticated users can manage monitor cannons inventory"
    ON public.inventario_canhoes_monitores FOR ALL
    USING (auth.role() = 'authenticated'::text)
    WITH CHECK (auth.role() = 'authenticated'::text);

-- Tabela de Inventário Chuveiros/Lava-olhos
CREATE TABLE IF NOT EXISTS public.inventario_chuveiros_lava_olhos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
    id_equipamento TEXT NOT NULL UNIQUE,
    localizacao TEXT,
    marca TEXT,
    modelo TEXT,
    data_cadastro DATE DEFAULT CURRENT_DATE,
    user_id UUID REFERENCES auth.users(id) ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS inventario_chuveiros_lava_olhos_user_id_idx ON public.inventario_chuveiros_lava_olhos(user_id);
ALTER TABLE public.inventario_chuveiros_lava_olhos ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Authenticated users can manage eyewash stations inventory"
    ON public.inventario_chuveiros_lava_olhos FOR ALL
    USING (auth.role() = 'authenticated'::text)
    WITH CHECK (auth.role() = 'authenticated'::text);

-- Tabela de Inventário Alarmes
CREATE TABLE IF NOT EXISTS public.inventario_alarmes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
    id_sistema TEXT NOT NULL UNIQUE,
    localizacao TEXT NOT NULL,
    marca TEXT,
    modelo TEXT,
    data_cadastro DATE DEFAULT CURRENT_DATE,
    user_id UUID REFERENCES auth.users(id) ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS inventario_alarmes_user_id_idx ON public.inventario_alarmes(user_id);
ALTER TABLE public.inventario_alarmes ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Authenticated users can manage alarms inventory"
    ON public.inventario_alarmes FOR ALL
    USING (auth.role() = 'authenticated'::text)
    WITH CHECK (auth.role() = 'authenticated'::text);

-- Tabela de Abrigos
CREATE TABLE IF NOT EXISTS public.abrigos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
    id_abrigo TEXT NOT NULL UNIQUE,
    cliente TEXT,
    local TEXT,
    itens_json JSONB,
    user_id UUID REFERENCES auth.users(id) ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS abrigos_user_id_idx ON public.abrigos(user_id);
ALTER TABLE public.abrigos ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Authenticated users can manage shelters"
    ON public.abrigos FOR ALL
    USING (auth.role() = 'authenticated'::text)
    WITH CHECK (auth.role() = 'authenticated'::text);

-- ============================================
-- TABELAS DE INSPEÇÕES
-- ============================================

-- Tabela de Inspeções SCBA
CREATE TABLE IF NOT EXISTS public.inspecoes_scba (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
    data_inspecao DATE DEFAULT CURRENT_DATE,
    numero_serie_equipamento TEXT NOT NULL,
    status_geral TEXT,
    resultados_json JSONB,
    inspetor TEXT,
    data_proxima_inspecao DATE,
    user_id UUID REFERENCES auth.users(id) ON DELETE SET NULL,
    FOREIGN KEY (numero_serie_equipamento) REFERENCES public.conjuntos_autonomos(numero_serie_equipamento)
);

CREATE INDEX IF NOT EXISTS inspecoes_scba_user_id_idx ON public.inspecoes_scba(user_id);
CREATE INDEX IF NOT EXISTS inspecoes_scba_numero_serie_idx ON public.inspecoes_scba(numero_serie_equipamento);
ALTER TABLE public.inspecoes_scba ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Authenticated users can manage SCBA inspections"
    ON public.inspecoes_scba FOR ALL
    USING (auth.role() = 'authenticated'::text)
    WITH CHECK (auth.role() = 'authenticated'::text);

-- Tabela de Inspeções Multigás
CREATE TABLE IF NOT EXISTS public.inspecoes_multigas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
    data_teste DATE DEFAULT CURRENT_DATE,
    id_equipamento TEXT NOT NULL,
    tipo_teste TEXT,
    resultado_teste TEXT,
    LEL_referencia NUMERIC,
    O2_referencia NUMERIC,
    H2S_referencia INTEGER,
    CO_referencia INTEGER,
    LEL_encontrado NUMERIC,
    O2_encontrado NUMERIC,
    H2S_encontrado INTEGER,
    CO_encontrado INTEGER,
    observacoes TEXT,
    plano_de_acao TEXT,
    inspetor TEXT,
    data_proximo_teste DATE,
    user_id UUID REFERENCES auth.users(id) ON DELETE SET NULL,
    FOREIGN KEY (id_equipamento) REFERENCES public.inventario_multigas(id_equipamento)
);

CREATE INDEX IF NOT EXISTS inspecoes_multigas_user_id_idx ON public.inspecoes_multigas(user_id);
CREATE INDEX IF NOT EXISTS inspecoes_multigas_id_equipamento_idx ON public.inspecoes_multigas(id_equipamento);
ALTER TABLE public.inspecoes_multigas ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Authenticated users can manage multigas inspections"
    ON public.inspecoes_multigas FOR ALL
    USING (auth.role() = 'authenticated'::text)
    WITH CHECK (auth.role() = 'authenticated'::text);

-- Tabela de Inspeções Câmaras de Espuma
CREATE TABLE IF NOT EXISTS public.inspecoes_camaras_espuma (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
    data_inspecao DATE DEFAULT CURRENT_DATE,
    id_camara TEXT NOT NULL,
    tipo_inspecao TEXT,
    status_geral TEXT,
    plano_de_acao TEXT,
    resultados_json JSONB,
    link_foto_nao_conformidade TEXT,
    inspetor TEXT,
    data_proxima_inspecao DATE,
    user_id UUID REFERENCES auth.users(id) ON DELETE SET NULL,
    FOREIGN KEY (id_camara) REFERENCES public.inventario_camaras_espuma(id_camara)
);

CREATE INDEX IF NOT EXISTS inspecoes_camaras_espuma_user_id_idx ON public.inspecoes_camaras_espuma(user_id);
CREATE INDEX IF NOT EXISTS inspecoes_camaras_espuma_id_camara_idx ON public.inspecoes_camaras_espuma(id_camara);
ALTER TABLE public.inspecoes_camaras_espuma ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Authenticated users can manage foam chambers inspections"
    ON public.inspecoes_camaras_espuma FOR ALL
    USING (auth.role() = 'authenticated'::text)
    WITH CHECK (auth.role() = 'authenticated'::text);

-- Tabela de Inspeções Canhões Monitores
CREATE TABLE IF NOT EXISTS public.inspecoes_canhoes_monitores (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
    data_inspecao DATE DEFAULT CURRENT_DATE,
    id_equipamento TEXT NOT NULL,
    tipo_inspecao TEXT,
    status_geral TEXT,
    plano_de_acao TEXT,
    resultados_json JSONB,
    link_foto_nao_conformidade TEXT,
    inspetor TEXT,
    data_proxima_inspecao DATE,
    user_id UUID REFERENCES auth.users(id) ON DELETE SET NULL,
    FOREIGN KEY (id_equipamento) REFERENCES public.inventario_canhoes_monitores(id_equipamento)
);

CREATE INDEX IF NOT EXISTS inspecoes_canhoes_monitores_user_id_idx ON public.inspecoes_canhoes_monitores(user_id);
CREATE INDEX IF NOT EXISTS inspecoes_canhoes_monitores_id_equipamento_idx ON public.inspecoes_canhoes_monitores(id_equipamento);
ALTER TABLE public.inspecoes_canhoes_monitores ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Authenticated users can manage monitor cannons inspections"
    ON public.inspecoes_canhoes_monitores FOR ALL
    USING (auth.role() = 'authenticated'::text)
    WITH CHECK (auth.role() = 'authenticated'::text);

-- Tabela de Inspeções Chuveiros/Lava-olhos
CREATE TABLE IF NOT EXISTS public.inspecoes_chuveiros_lava_olhos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
    data_inspecao DATE DEFAULT CURRENT_DATE,
    id_equipamento TEXT NOT NULL,
    status_geral TEXT,
    plano_de_acao TEXT,
    resultados_json JSONB,
    link_foto_nao_conformidade TEXT,
    inspetor TEXT,
    data_proxima_inspecao DATE,
    user_id UUID REFERENCES auth.users(id) ON DELETE SET NULL,
    FOREIGN KEY (id_equipamento) REFERENCES public.inventario_chuveiros_lava_olhos(id_equipamento)
);

CREATE INDEX IF NOT EXISTS inspecoes_chuveiros_lava_olhos_user_id_idx ON public.inspecoes_chuveiros_lava_olhos(user_id);
CREATE INDEX IF NOT EXISTS inspecoes_chuveiros_lava_olhos_id_equipamento_idx ON public.inspecoes_chuveiros_lava_olhos(id_equipamento);
ALTER TABLE public.inspecoes_chuveiros_lava_olhos ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Authenticated users can manage eyewash stations inspections"
    ON public.inspecoes_chuveiros_lava_olhos FOR ALL
    USING (auth.role() = 'authenticated'::text)
    WITH CHECK (auth.role() = 'authenticated'::text);

-- Tabela de Inspeções Alarmes
CREATE TABLE IF NOT EXISTS public.inspecoes_alarmes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
    data_inspecao DATE DEFAULT CURRENT_DATE,
    id_sistema TEXT NOT NULL,
    status_geral TEXT,
    plano_de_acao TEXT,
    resultados_json JSONB,
    link_foto_nao_conformidade TEXT,
    inspetor TEXT,
    data_proxima_inspecao DATE,
    user_id UUID REFERENCES auth.users(id) ON DELETE SET NULL,
    FOREIGN KEY (id_sistema) REFERENCES public.inventario_alarmes(id_sistema)
);

CREATE INDEX IF NOT EXISTS inspecoes_alarmes_user_id_idx ON public.inspecoes_alarmes(user_id);
CREATE INDEX IF NOT EXISTS inspecoes_alarmes_id_sistema_idx ON public.inspecoes_alarmes(id_sistema);
ALTER TABLE public.inspecoes_alarmes ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Authenticated users can manage alarms inspections"
    ON public.inspecoes_alarmes FOR ALL
    USING (auth.role() = 'authenticated'::text)
    WITH CHECK (auth.role() = 'authenticated'::text);

-- Tabela de Inspeções Abrigos
CREATE TABLE IF NOT EXISTS public.inspecoes_abrigos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
    data_inspecao DATE DEFAULT CURRENT_DATE,
    id_abrigo TEXT NOT NULL,
    status_geral TEXT,
    resultados_json JSONB,
    inspetor TEXT,
    data_proxima_inspecao DATE,
    user_id UUID REFERENCES auth.users(id) ON DELETE SET NULL,
    FOREIGN KEY (id_abrigo) REFERENCES public.abrigos(id_abrigo)
);

CREATE INDEX IF NOT EXISTS inspecoes_abrigos_user_id_idx ON public.inspecoes_abrigos(user_id);
CREATE INDEX IF NOT EXISTS inspecoes_abrigos_id_abrigo_idx ON public.inspecoes_abrigos(id_abrigo);
ALTER TABLE public.inspecoes_abrigos ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Authenticated users can manage shelters inspections"
    ON public.inspecoes_abrigos FOR ALL
    USING (auth.role() = 'authenticated'::text)
    WITH CHECK (auth.role() = 'authenticated'::text);

-- ============================================
-- TABELAS DE LOG DE AÇÕES CORRETIVAS
-- ============================================

-- Log de Ações Extintores
CREATE TABLE IF NOT EXISTS public.log_acoes_extintores (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
    data_acao DATE DEFAULT CURRENT_DATE,
    id_equipamento TEXT NOT NULL,
    problema_original TEXT,
    acao_realizada TEXT,
    responsavel_acao TEXT,
    id_substituto TEXT,
    photo_link TEXT,
    user_id UUID REFERENCES auth.users(id) ON DELETE SET NULL,
    FOREIGN KEY (id_equipamento) REFERENCES public.extintores(numero_identificacao)
);

CREATE INDEX IF NOT EXISTS log_acoes_extintores_user_id_idx ON public.log_acoes_extintores(user_id);
CREATE INDEX IF NOT EXISTS log_acoes_extintores_id_equipamento_idx ON public.log_acoes_extintores(id_equipamento);
ALTER TABLE public.log_acoes_extintores ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Authenticated users can manage extinguisher action logs"
    ON public.log_acoes_extintores FOR ALL
    USING (auth.role() = 'authenticated'::text)
    WITH CHECK (auth.role() = 'authenticated'::text);

-- Log de Ações SCBA
CREATE TABLE IF NOT EXISTS public.log_acoes_scba (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
    data_acao DATE DEFAULT CURRENT_DATE,
    id_equipamento TEXT NOT NULL,
    problema_original TEXT,
    acao_realizada TEXT,
    responsavel_acao TEXT,
    user_id UUID REFERENCES auth.users(id) ON DELETE SET NULL,
    FOREIGN KEY (id_equipamento) REFERENCES public.conjuntos_autonomos(numero_serie_equipamento)
);

CREATE INDEX IF NOT EXISTS log_acoes_scba_user_id_idx ON public.log_acoes_scba(user_id);
CREATE INDEX IF NOT EXISTS log_acoes_scba_id_equipamento_idx ON public.log_acoes_scba(id_equipamento);
ALTER TABLE public.log_acoes_scba ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Authenticated users can manage SCBA action logs"
    ON public.log_acoes_scba FOR ALL
    USING (auth.role() = 'authenticated'::text)
    WITH CHECK (auth.role() = 'authenticated'::text);

-- Log de Ações Multigás
CREATE TABLE IF NOT EXISTS public.log_acoes_multigas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
    data_acao DATE DEFAULT CURRENT_DATE,
    id_equipamento TEXT NOT NULL,
    problema_original TEXT,
    acao_realizada TEXT,
    responsavel_acao TEXT,
    photo_link TEXT,
    user_id UUID REFERENCES auth.users(id) ON DELETE SET NULL,
    FOREIGN KEY (id_equipamento) REFERENCES public.inventario_multigas(id_equipamento)
);

CREATE INDEX IF NOT EXISTS log_acoes_multigas_user_id_idx ON public.log_acoes_multigas(user_id);
CREATE INDEX IF NOT EXISTS log_acoes_multigas_id_equipamento_idx ON public.log_acoes_multigas(id_equipamento);
ALTER TABLE public.log_acoes_multigas ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Authenticated users can manage multigas action logs"
    ON public.log_acoes_multigas FOR ALL
    USING (auth.role() = 'authenticated'::text)
    WITH CHECK (auth.role() = 'authenticated'::text);

-- Log de Ações Câmaras de Espuma
CREATE TABLE IF NOT EXISTS public.log_acoes_camaras_espuma (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
    data_acao DATE DEFAULT CURRENT_DATE,
    id_equipamento TEXT NOT NULL,
    problema_original TEXT,
    acao_realizada TEXT,
    responsavel_acao TEXT,
    user_id UUID REFERENCES auth.users(id) ON DELETE SET NULL,
    FOREIGN KEY (id_equipamento) REFERENCES public.inventario_camaras_espuma(id_camara)
);

CREATE INDEX IF NOT EXISTS log_acoes_camaras_espuma_user_id_idx ON public.log_acoes_camaras_espuma(user_id);
CREATE INDEX IF NOT EXISTS log_acoes_camaras_espuma_id_equipamento_idx ON public.log_acoes_camaras_espuma(id_equipamento);
ALTER TABLE public.log_acoes_camaras_espuma ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Authenticated users can manage foam chambers action logs"
    ON public.log_acoes_camaras_espuma FOR ALL
    USING (auth.role() = 'authenticated'::text)
    WITH CHECK (auth.role() = 'authenticated'::text);

-- Log de Ações Canhões Monitores
CREATE TABLE IF NOT EXISTS public.log_acoes_canhoes_monitores (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
    data_acao DATE DEFAULT CURRENT_DATE,
    id_equipamento TEXT NOT NULL,
    problema_original TEXT,
    acao_realizada TEXT,
    responsavel_acao TEXT,
    photo_link TEXT,
    user_id UUID REFERENCES auth.users(id) ON DELETE SET NULL,
    FOREIGN KEY (id_equipamento) REFERENCES public.inventario_canhoes_monitores(id_equipamento)
);

CREATE INDEX IF NOT EXISTS log_acoes_canhoes_monitores_user_id_idx ON public.log_acoes_canhoes_monitores(user_id);
CREATE INDEX IF NOT EXISTS log_acoes_canhoes_monitores_id_equipamento_idx ON public.log_acoes_canhoes_monitores(id_equipamento);
ALTER TABLE public.log_acoes_canhoes_monitores ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Authenticated users can manage monitor cannons action logs"
    ON public.log_acoes_canhoes_monitores FOR ALL
    USING (auth.role() = 'authenticated'::text)
    WITH CHECK (auth.role() = 'authenticated'::text);

-- Log de Ações Chuveiros/Lava-olhos
CREATE TABLE IF NOT EXISTS public.log_acoes_chuveiros_lava_olhos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
    data_acao DATE DEFAULT CURRENT_DATE,
    id_equipamento TEXT NOT NULL,
    problema_original TEXT,
    acao_realizada TEXT,
    responsavel_acao TEXT,
    photo_link TEXT,
    user_id UUID REFERENCES auth.users(id) ON DELETE SET NULL,
    FOREIGN KEY (id_equipamento) REFERENCES public.inventario_chuveiros_lava_olhos(id_equipamento)
);

CREATE INDEX IF NOT EXISTS log_acoes_chuveiros_lava_olhos_user_id_idx ON public.log_acoes_chuveiros_lava_olhos(user_id);
CREATE INDEX IF NOT EXISTS log_acoes_chuveiros_lava_olhos_id_equipamento_idx ON public.log_acoes_chuveiros_lava_olhos(id_equipamento);
ALTER TABLE public.log_acoes_chuveiros_lava_olhos ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Authenticated users can manage eyewash stations action logs"
    ON public.log_acoes_chuveiros_lava_olhos FOR ALL
    USING (auth.role() = 'authenticated'::text)
    WITH CHECK (auth.role() = 'authenticated'::text);

-- Log de Ações Alarmes
CREATE TABLE IF NOT EXISTS public.log_acoes_alarmes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
    data_acao DATE DEFAULT CURRENT_DATE,
    id_equipamento TEXT NOT NULL,
    problema_original TEXT,
    acao_realizada TEXT,
    responsavel_acao TEXT,
    photo_link TEXT,
    user_id UUID REFERENCES auth.users(id) ON DELETE SET NULL,
    FOREIGN KEY (id_equipamento) REFERENCES public.inventario_alarmes(id_sistema)
);

CREATE INDEX IF NOT EXISTS log_acoes_alarmes_user_id_idx ON public.log_acoes_alarmes(user_id);
CREATE INDEX IF NOT EXISTS log_acoes_alarmes_id_equipamento_idx ON public.log_acoes_alarmes(id_equipamento);
ALTER TABLE public.log_acoes_alarmes ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Authenticated users can manage alarms action logs"
    ON public.log_acoes_alarmes FOR ALL
    USING (auth.role() = 'authenticated'::text)
    WITH CHECK (auth.role() = 'authenticated'::text);

-- Log de Ações Abrigos
CREATE TABLE IF NOT EXISTS public.log_acoes_abrigos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
    data_acao DATE DEFAULT CURRENT_DATE,
    id_equipamento TEXT NOT NULL,
    problema_original TEXT,
    acao_realizada TEXT,
    responsavel_acao TEXT,
    user_id UUID REFERENCES auth.users(id) ON DELETE SET NULL,
    FOREIGN KEY (id_equipamento) REFERENCES public.abrigos(id_abrigo)
);

CREATE INDEX IF NOT EXISTS log_acoes_abrigos_user_id_idx ON public.log_acoes_abrigos(user_id);
CREATE INDEX IF NOT EXISTS log_acoes_abrigos_id_equipamento_idx ON public.log_acoes_abrigos(id_equipamento);
ALTER TABLE public.log_acoes_abrigos ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Authenticated users can manage shelters action logs"
    ON public.log_acoes_abrigos FOR ALL
    USING (auth.role() = 'authenticated'::text)
    WITH CHECK (auth.role() = 'authenticated'::text);

-- ============================================
-- TABELAS AUXILIARES ADICIONAIS
-- ============================================

-- Log de Baixa de Extintores
CREATE TABLE IF NOT EXISTS public.log_baixa_extintores (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
    data_baixa DATE DEFAULT CURRENT_DATE,
    numero_identificacao TEXT NOT NULL,
    motivo_condenacao TEXT,
    responsavel_baixa TEXT,
    numero_identificacao_substituto TEXT,
    observacoes TEXT,
    link_foto_evidencia TEXT,
    user_id UUID REFERENCES auth.users(id) ON DELETE SET NULL,
    FOREIGN KEY (numero_identificacao) REFERENCES public.extintores(numero_identificacao)
);

CREATE INDEX IF NOT EXISTS log_baixa_extintores_user_id_idx ON public.log_baixa_extintores(user_id);
CREATE INDEX IF NOT EXISTS log_baixa_extintores_numero_identificacao_idx ON public.log_baixa_extintores(numero_identificacao);
ALTER TABLE public.log_baixa_extintores ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Authenticated users can manage extinguisher disposal logs"
    ON public.log_baixa_extintores FOR ALL
    USING (auth.role() = 'authenticated'::text)
    WITH CHECK (auth.role() = 'authenticated'::text);

