/*
# [Initial Schema Setup]
This script sets up the initial database schema for the ISF IA application. It creates the necessary tables for user profiles and equipment inventory, along with required data types and security policies.

## Query Description: This operation is structural and foundational. It does not modify or delete any existing data but creates the necessary tables for the application to function. It's safe to run on a new project. It includes:
1.  Creation of ENUM types for equipment status and type.
2.  Creation of a `profiles` table to store user-specific data, linked to Supabase's authentication.
3.  Creation of an `equipment` table for inventory management.
4.  Enabling Row Level Security (RLS) and defining basic access policies.

## Metadata:
- Schema-Category: "Structural"
- Impact-Level: "Low"
- Requires-Backup: false
- Reversible: true (by dropping the created tables and types)

## Structure Details:
- Tables created: `profiles`, `equipment`
- Types created: `equipment_type`, `equipment_status`
- RLS Policies:
  - `profiles`: Users can view/update their own profile.
  - `equipment`: Authenticated users can perform all operations.

## Security Implications:
- RLS Status: Enabled on `profiles` and `equipment`.
- Policy Changes: Yes, new policies are created.
- Auth Requirements: Policies are based on `auth.uid()` and authenticated roles.

## Performance Impact:
- Indexes: Primary keys are indexed by default. No other indexes added at this stage.
- Triggers: A trigger is added to create a user profile upon new user sign-up.
- Estimated Impact: Low. The setup is for initial structure.
*/

-- 1. Create ENUM types for controlled vocabularies
CREATE TYPE public.equipment_type AS ENUM (
    'extintor',
    'mangueira',
    'abrigo',
    'scba',
    'chuveiro_lavaolhos',
    'camara_espuma',
    'multigas',
    'alarme',
    'canhao_monitor'
);

CREATE TYPE public.equipment_status AS ENUM (
    'ok',
    'vencido',
    'pendente',
    'nao_conforme',
    'baixado'
);


-- 2. Create Profiles table to store user data
CREATE TABLE public.profiles (
  id UUID NOT NULL PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  full_name TEXT,
  avatar_url TEXT,
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Set up Row Level Security (RLS)
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Public profiles are viewable by everyone."
  ON public.profiles FOR SELECT
  USING ( true );

CREATE POLICY "Users can insert their own profile."
  ON public.profiles FOR INSERT
  WITH CHECK ( auth.uid() = id );

CREATE POLICY "Users can update own profile."
  ON public.profiles FOR UPDATE
  USING ( auth.uid() = id );

-- This trigger automatically creates a profile entry when a new user signs up
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO public.profiles (id, full_name, avatar_url)
  VALUES (new.id, new.raw_user_meta_data->>'full_name', new.raw_user_meta_data->>'avatar_url');
  RETURN new;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE PROCEDURE public.handle_new_user();


-- 3. Create Equipment table for inventory
CREATE TABLE public.equipment (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
    equipment_id TEXT NOT NULL UNIQUE, -- e.g., EXT-001
    equipment_type public.equipment_type NOT NULL,
    status public.equipment_status NOT NULL DEFAULT 'ok',
    specifications JSONB, -- For flexible data like brand, model, etc.
    localizacao TEXT,
    proxima_inspecao DATE,
    data_validade DATE,
    qr_code TEXT,
    user_id UUID REFERENCES auth.users(id) ON DELETE SET NULL
);

-- Set up Row Level Security (RLS)
ALTER TABLE public.equipment ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Authenticated users can manage equipment."
  ON public.equipment FOR ALL
  USING ( auth.role() = 'authenticated'::text )
  WITH CHECK ( auth.role() = 'authenticated'::text );

-- 4. Add some mock data for development
INSERT INTO public.equipment (equipment_id, equipment_type, status, localizacao, proxima_inspecao, data_validade)
VALUES
('EXT-001', 'extintor', 'ok', 'Prédio A - Andar 1', '2025-12-01', '2026-05-15'),
('EXT-002', 'extintor', 'vencido', 'Prédio B - Térreo', '2025-02-10', '2025-08-20'),
('MANG-001', 'mangueira', 'ok', 'Garagem G1', '2026-01-20', '2030-01-01'),
('ABR-005', 'abrigo', 'pendente', 'Prédio A - Andar 3', '2025-07-11', '2028-07-10'),
('SCBA-001', 'scba', 'ok', 'Sala de Brigada', '2025-09-01', '2027-09-01'),
('EXT-003', 'extintor', 'ok', 'Oficina', '2026-03-01', '2027-01-10'),
('EXT-004', 'extintor', 'vencido', 'Almoxarifado', '2025-01-05', '2025-06-01');
