name: Invitation Detection System

on:
  schedule:
    # Executa a cada 2 horas para verificar tentativas de acesso não autorizadas
    - cron: '0 */2 * * *'
  workflow_dispatch:
    # Permite execução manual

jobs:
  detect-and-create-invitations:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install google-auth google-auth-oauthlib google-auth-httplib2 google-api-python-client
        
    - name: Detect Unauthorized Access and Create Invitations
      env:
        GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
        MATRIX_SHEETS_ID: ${{ secrets.MATRIX_SHEETS_ID }}
        APP_URL: ${{ secrets.APP_URL }}
      run: |
        python .github/scripts/send_invitation_email.py

  health-check:
    runs-on: ubuntu-latest
    needs: [detect-and-create-invitations]
    if: always()
    
    steps:
    - name: Invitation Detection Health Check
      run: |
        echo "📧 Sistema de Detecção de Convites Automáticos"
        echo "✅ Status: Operacional"
        echo "⏰ Última execução: $(date)"
        echo ""
        echo "📊 Fluxo do Sistema:"
        echo "   1. Detecta tentativas não autorizadas (a cada 2h)"
        echo "   2. Cria notificações em 'notificacoes_pendentes'"
        echo "   3. Sistema de emails processa e envia (a cada 5min)"
        echo ""
        echo "🔍 Variáveis configuradas:"
        echo "   - Credenciais Google: $([[ -n \"$GOOGLE_CREDENTIALS\" ]] && echo '✅ OK' || echo '❌ Faltando')"
        echo "   - Matrix Sheets ID: $([[ -n \"$MATRIX_SHEETS_ID\" ]] && echo '✅ OK' || echo '❌ Faltando')"
        echo "   - URL do App: $([[ -n \"$APP_URL\" ]] && echo '✅ OK' || echo '❌ Faltando')"
      env:
        GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
        MATRIX_SHEETS_ID: ${{ secrets.MATRIX_SHEETS_ID }}
        APP_URL: ${{ secrets.APP_URL }}
