name: Process Email Notifications

on:
  schedule:
    # Executa aos 2, 7, 12, 17, 22, 27, 32, 37, 42, 47, 52, 57 minutos de cada hora
    # Evita o início de cada hora (minuto 0) que é quando há mais carga no GitHub Actions
    - cron: '2,7,12,17,22,27,32,37,42,47,52,57 * * * *'
  workflow_dispatch:
    # Permite execução manual

jobs:
  process-notifications:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install google-auth google-auth-oauthlib google-auth-httplib2 google-api-python-client jinja2
        
    - name: Process Pending Notifications
      env:
        SMTP_SERVER: ${{ secrets.SMTP_SERVER }}
        SMTP_PORT: ${{ secrets.SMTP_PORT }}
        SMTP_USERNAME: ${{ secrets.SMTP_USERNAME }}
        SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
        FROM_EMAIL: ${{ secrets.FROM_EMAIL }}
        FROM_NAME: ${{ secrets.FROM_NAME }}
        GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
        MATRIX_SHEETS_ID: ${{ secrets.MATRIX_SHEETS_ID }}
      run: |
        python .github/scripts/send_email.py
